AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'a custom rule implementation for aws config

  '
Parameters:
  MasterUser:
    Description: master user for rds instance
    Default: master
    Type: String
  MasterPasssword:
    Description: master password for rds instance
    Default: change_me
    Type: String
Resources:
  RDSLogPersistenceRemediationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://frankfurt-testing/config/cc0cdd8037efc73c30390a3aa9e78edb
      Handler: app.lambda_handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - RDSFunctionsIAMRole
        - Arn
  RDSLogPersistenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://frankfurt-testing/config/7488156c46b6857307afde5fade98bfc
      Handler: app.lambda_handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - RDSFunctionsIAMRole
        - Arn
  RDSFunctionsIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSConfigRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: lambda_rds_access
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - rds:*
            Resource: '*'
  ConfigSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: AWS Config Notifications
  LabDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: db.t2.small
      Engine: MySQL
      EngineVersion: 8.0.16
      PubliclyAccessible: false
      MasterUsername:
        Ref: MasterUser
      MasterUserPassword:
        Ref: MasterPasssword
Outputs:
  RDSLogPersistenceFunction:
    Description: lambda function that implements a config rule
    Value:
      Fn::GetAtt:
      - RDSLogPersistenceFunction
      - Arn
  ConfigSNSTopic:
    Description: sns topic for aws config
    Value:
      Ref: ConfigSNSTopic
